// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cockroach

import (
	"context"
	admindiv2 "github.com/aqaurius6666/citizen-v/src/internal/db/admindiv"
	campaign2 "github.com/aqaurius6666/citizen-v/src/internal/db/campaign"
	citizen2 "github.com/aqaurius6666/citizen-v/src/internal/db/citizen"
	"github.com/aqaurius6666/citizen-v/src/internal/db/cockroach/admindiv"
	"github.com/aqaurius6666/citizen-v/src/internal/db/cockroach/campaign"
	"github.com/aqaurius6666/citizen-v/src/internal/db/cockroach/citizen"
	"github.com/aqaurius6666/citizen-v/src/internal/db/cockroach/role"
	"github.com/aqaurius6666/citizen-v/src/internal/db/cockroach/user"
	role2 "github.com/aqaurius6666/citizen-v/src/internal/db/role"
	user2 "github.com/aqaurius6666/citizen-v/src/internal/db/user"
	"github.com/aqaurius6666/go-utils/database/cockroach"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from server.cdb.wire.go:

func initServerCDBRepo(ctx context.Context, logger *logrus.Logger, opts ServerCDBOptions) (*ServerCDBRepo, error) {
	string2 := opts.Dsn
	config := opts.Cfg
	db, err := cockroach.NewCDBConnection(string2, config)
	if err != nil {
		return nil, err
	}
	cdbRepository := cockroach.InitCDBRepository(ctx, logger, db)
	userCDBRepo, err := user.InitUserCDBRepo(ctx, logger, db)
	if err != nil {
		return nil, err
	}
	roleCDBRepo, err := role.InitRoleCDBRepo(ctx, logger, db)
	if err != nil {
		return nil, err
	}
	adminDivCDBRepo, err := admindiv.InitAdminDivCDBRepo(ctx, logger, db)
	if err != nil {
		return nil, err
	}
	citizenCDBRepo, err := citizen.InitCitizenCDBRepo(ctx, logger, db)
	if err != nil {
		return nil, err
	}
	campaignCDBRepo, err := campaign.InitCampaignCDBRepo(ctx, logger, db)
	if err != nil {
		return nil, err
	}
	serverCDBRepo := &ServerCDBRepo{
		CDBRepository: cdbRepository,
		UserRepo:      userCDBRepo,
		RoleRepo:      roleCDBRepo,
		AdminDivRepo:  adminDivCDBRepo,
		CitizenRepo:   citizenCDBRepo,
		CampaignRepo:  campaignCDBRepo,
	}
	return serverCDBRepo, nil
}

// server.cdb.wire.go:

type ServerCDBOptions struct {
	Cfg *gorm.Config
	Dsn string
}

func InitServerCDBRepo(ctx context.Context, logger *logrus.Logger, opts ServerCDBOptions) (*ServerCDBRepo, error) {
	s, err := initServerCDBRepo(ctx, logger, opts)
	if err != nil {
		return nil, err
	}
	s.SetInterfaces(&user2.User{}, &role2.Role{}, &admindiv2.AdminDiv{}, &citizen2.Citizen{}, &campaign2.Campaign{})
	return s, nil
}
