// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"context"
	"github.com/aqaurius6666/go-utils/database/cockroach"
	"github.com/aqaurius6666/go-utils/logger"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from user.cdb.wire.go:

func InitUserCDBRepo(ctx context.Context, logger *logrus.Logger, db *gorm.DB) (*UserCDBRepo, error) {
	cdbRepository := cockroach.InitCDBRepository(ctx, logger, db)
	userCDBRepo := &UserCDBRepo{
		CDBRepository: cdbRepository,
	}
	return userCDBRepo, nil
}

func InitUserCDBMockRepo(ctx context.Context, db *gorm.DB) (*UserCDBRepo, error) {
	logrusLogger := logger.InitLoggerWithoutCLIContext()
	cdbRepository := cockroach.InitCDBRepository(ctx, logrusLogger, db)
	userCDBRepo := &UserCDBRepo{
		CDBRepository: cdbRepository,
	}
	return userCDBRepo, nil
}
