// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package model

import (
	"context"
	"github.com/aqaurius6666/citizen-v/src/internal/db"
	"github.com/sirupsen/logrus"
)

// Injectors from model.wire.go:

func InitModel(ctx context.Context, logger *logrus.Logger, repo db.ServerRepo) (*ServerModel, error) {
	roleModel := &RoleModel{
		Repo: repo,
	}
	userModel := &UserModel{
		Repo: repo,
	}
	adminDivModel := &AdminDivModel{
		Repo: repo,
	}
	serverModel := &ServerModel{
		Role:     roleModel,
		User:     userModel,
		AdminDiv: adminDivModel,
	}
	return serverModel, nil
}
