version: "3.7"
networks:
  main:
    name: go-go
services:
  cdb:
    image: cockroachdb/cockroach:v21.1.6
    ports:
      - "20000:26257"
    command: start-single-node --insecure
    volumes:
      - "../../.db:/cockroach/cockroach-data"
    networks:
      - main
  mainservice:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "../../:/app"
      - "/home/aqaurius6666/go:/go"
    ports:
      - "9091:8080"
      - "2345:2345"
    depends_on:
      - cdb
    command:
      - /bin/sh
      - -c
      - |
        air
    environment:
      - DISABLE_TRACING=true
      - DISABLE_PROFILER=true
      - VERSION=0.0.1
      - PORT=8080
      - GRPC_PORT=50051
      - PROMETHEUS=7070
      - PPROF_PORT=6000
      - DISABLE_STATS=true
      - DB_URI=postgresql://root:root@cdb:26257/defaultdb?sslmode=disable
      # - DB_URI=postgres://tlaawkagdaojbb:764a29a44844722107d7408ca01c583fdbf1c49c0f19ab2aecac1a374bd72d81@ec2-54-161-164-220.compute-1.amazonaws.com:5432/d8i5f537dtn5bd
      - LOG_LEVEL=debug
      - LOG_FORMAT=plain
      - JWT_SECRET_KEY=hangngungok-_-
      - SERVER_KEY=vuvjppro.-.
      - GCFLAGS
    networks:
      - main
