version: "3.7"
networks:
  main:
    name: go-go
services:
  cdb:
    image: cockroachdb/cockroach:v21.1.6
    ports:
      - "26257:26257"
    command: start-single-node --insecure
    # volumes:
    #   - "../../.db:/cockroach/cockroach-data"
    networks:
      - main
  mainservice:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: dev
    volumes:
      - "../../:/app"
      - "/home/aqaurius6666/go:/go"
    ports:
      - "9091:80"
      - "2345:2345"
    depends_on:
      - cdb
    command:
      - /bin/sh
      - -c
      - |
        air
    environment:
      - DISABLE_TRACING=true
      - DISABLE_PROFILER=true
      - VERSION=0.0.1
      - HTTP_PORT=80
      - GRPC_PORT=50051
      - PROMETHEUS=7070
      - PPROF_PORT=6000
      - DISABLE_STATS=true
      - DB_URI=postgresql://root:root@main-cdb:26257/defaultdb?sslmode=disable
      - LOG_LEVEL=debug
      - LOG_FORMAT=plain
      - GCFLAGS
    networks:
      - main
