// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"context"
	"github.com/aqaurius6666/boilerplate-server-go/src/internal/db"
	"github.com/gin-gonic/gin"
	"github.com/sirupsen/logrus"
)

// Injectors from api.wire.go:

func InitApiServer(ctx context.Context, logger *logrus.Logger, opts ApiServerOptions) (*ApiServer, error) {
	engine := gin.New()
	serverRepo := opts.MainRepo
	indexController := &IndexController{
		Repo: serverRepo,
	}
	apiServer := &ApiServer{
		G:          engine,
		logger:     logger,
		serverRepo: serverRepo,
		Index:      indexController,
	}
	return apiServer, nil
}

// api.wire.go:

type ApiServerOptions struct {
	MainRepo db.ServerRepo
}
