// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package role

import (
	"context"
	"github.com/aquarius6666/go-utils/database/cockroach"
	"github.com/aquarius6666/go-utils/logger"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from role.cdb.wire.go:

func InitRoleCDBRepo(ctx context.Context, logger *logrus.Logger, db *gorm.DB) (*RoleCDBRepo, error) {
	cdbRepository := cockroach.InitCDBRepository(ctx, logger, db)
	roleCDBRepo := &RoleCDBRepo{
		CDBRepository: cdbRepository,
	}
	return roleCDBRepo, nil
}

func InitRoleCDBMockRepo(ctx context.Context, db *gorm.DB) (*RoleCDBRepo, error) {
	logrusLogger := logger.InitLoggerWithoutCLIContext()
	cdbRepository := cockroach.InitCDBRepository(ctx, logrusLogger, db)
	roleCDBRepo := &RoleCDBRepo{
		CDBRepository: cdbRepository,
	}
	return roleCDBRepo, nil
}
