// Code generated by swagger.main.go. DO NOT EDIT.
package swagger

var API_JSON = `{
  "swagger": "2.0",
  "info": {
    "title": "api.proto",
    "version": "Thu, 23 Dec 2021 13:39:40 +07"
  },
  "tags": [
    {
      "name": "Api"
    }
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/administrative-divisions": {
      "get": {
        "operationId": "Api_GetAdminDiv",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvGetAdminDivResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "code",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "superiorId",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "type",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "id",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "offset",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "CallerId",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Api"
        ]
      },
      "post": {
        "operationId": "Api_PostAdminDiv",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPostAdminDivResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/citizenvPostAdminDivRequest"
            }
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/administrative-divisions/options": {
      "get": {
        "operationId": "Api_GetAdminDivOptions",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvGetAdminDivOptionsResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "superiorId",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "CallerId",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/administrative-divisions/{id}": {
      "get": {
        "operationId": "Api_GetOneAdminDiv",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvGetOneAdminDivResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "message"
          },
          {
            "name": "CallerId",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Api"
        ]
      },
      "put": {
        "operationId": "Api_PutOneAdminDiv",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPutOneAdminDivResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "message"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "CallerId": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/auth": {
      "get": {
        "operationId": "Api_GetAuth",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvGetAuthResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "CallerId",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/auth/login": {
      "post": {
        "operationId": "Api_PostLogin",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPostLoginResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/citizenvPostLoginRequest"
            }
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/auth/password": {
      "post": {
        "operationId": "Api_PostAuthPassword",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPostAuthPasswordResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/citizenvPostAuthPasswordRequest"
            }
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/auth/register": {
      "post": {
        "operationId": "Api_PostRegister",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPostRegisterResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/citizenvPostRegisterRequest"
            }
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/campaigns": {
      "post": {
        "operationId": "Api_PostCampaign",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPostCampaignResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/citizenvPostCampaignRequest"
            }
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/citizens": {
      "get": {
        "operationId": "Api_GetCitizen",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvGetCitizenResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "pid",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "birthday",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "id",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "adminDivId",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "adminDivCode",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "offset",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "CallerId",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "adminDivCodes",
            "in": "query",
            "required": false,
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi"
          }
        ],
        "tags": [
          "Api"
        ]
      },
      "post": {
        "operationId": "Api_PostCitizen",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPostCitizenResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/citizenvPostCitizenRequest"
            }
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/citizens/{id}": {
      "get": {
        "operationId": "Api_GetOneCitizen",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvGetOneCitizenResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "message"
          }
        ],
        "tags": [
          "Api"
        ]
      },
      "delete": {
        "operationId": "Api_DeleteCitizen",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvDeleteCitizenResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "message"
          },
          {
            "name": "CallerId",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Api"
        ]
      },
      "put": {
        "operationId": "Api_PutOneCitizen",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPutOneCitizenResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "message"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "birthday": {
                  "type": "string",
                  "format": "int64"
                },
                "gender": {
                  "type": "string"
                },
                "nationality": {
                  "type": "string"
                },
                "fatherName": {
                  "type": "string"
                },
                "fatherPid": {
                  "type": "string"
                },
                "motherName": {
                  "type": "string"
                },
                "motherPid": {
                  "type": "string"
                },
                "jobName": {
                  "type": "string"
                },
                "pid": {
                  "type": "string"
                },
                "CallerId": {
                  "type": "string"
                },
                "religion": {
                  "type": "string"
                },
                "educationalLevel": {
                  "type": "string"
                },
                "adminDivCode": {
                  "type": "string"
                },
                "residencePlaceCode": {
                  "type": "string"
                },
                "hometownCode": {
                  "type": "string"
                },
                "currentPlaceCode": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/statistics/citizens": {
      "get": {
        "operationId": "Api_GetStatisticsCitizens",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvGetStatisticsCitizensResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "CallerId",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "adminDivCode",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "adminDivCodes",
            "in": "query",
            "required": false,
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi"
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/users": {
      "get": {
        "operationId": "Api_GetUsers",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvGetUsersResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "roleId",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "adminDivId",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "adminDivCode",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "username",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "offset",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/users/issue": {
      "post": {
        "operationId": "Api_PostUserIssue",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPostUserIssueResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/citizenvPostUserIssueRequest"
            }
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/users/{id}": {
      "get": {
        "operationId": "Api_GetUserOne",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvGetUserOneResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "message"
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/users/{id}/ban": {
      "post": {
        "operationId": "Api_PostUserBan",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPostUserActiveResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "message"
          },
          {
            "name": "Value",
            "in": "query",
            "required": false,
            "type": "boolean"
          },
          {
            "name": "CallerId",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Api"
        ]
      }
    },
    "/api/users/{id}/unban": {
      "post": {
        "operationId": "Api_PostUserUnban",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/citizenvPostUserActiveResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "pattern": "message"
          },
          {
            "name": "Value",
            "in": "query",
            "required": false,
            "type": "boolean"
          },
          {
            "name": "CallerId",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Api"
        ]
      }
    }
  },
  "definitions": {
    "DataResults": {
      "type": "object",
      "properties": {
        "adminDiv": {
          "$ref": "#/definitions/citizenvAdminDiv"
        },
        "campaign": {
          "$ref": "#/definitions/citizenvCampaign"
        }
      }
    },
    "citizenvAdminDiv": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "superiorId": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "subdiv": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/citizenvAdminDiv"
          }
        }
      }
    },
    "citizenvCampaign": {
      "type": "object",
      "properties": {
        "record": {
          "type": "integer",
          "format": "int32"
        },
        "isDone": {
          "type": "boolean"
        },
        "percent": {
          "type": "number",
          "format": "float"
        },
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "startTime": {
          "type": "string",
          "format": "int64"
        },
        "endTime": {
          "type": "string",
          "format": "int64"
        }
      }
    },
    "citizenvCitizen": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "birthday": {
          "type": "string",
          "format": "int64"
        },
        "gender": {
          "type": "string"
        },
        "nationality": {
          "type": "string"
        },
        "fatherName": {
          "type": "string"
        },
        "fatherPid": {
          "type": "string"
        },
        "motherName": {
          "type": "string"
        },
        "motherPid": {
          "type": "string"
        },
        "currentPlace": {
          "type": "string"
        },
        "jobName": {
          "type": "string"
        },
        "pid": {
          "type": "string"
        },
        "hometown": {
          "type": "string"
        },
        "religion": {
          "type": "string"
        },
        "educationalLevel": {
          "type": "string"
        },
        "adminDivCode": {
          "type": "string"
        },
        "residencePlace": {
          "type": "string"
        },
        "adminDivId": {
          "type": "string"
        },
        "residencePlaceCode": {
          "type": "string"
        },
        "currentPlaceCode": {
          "type": "string"
        },
        "hometownCode": {
          "type": "string"
        }
      }
    },
    "citizenvDeleteCitizenResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvDeleteCitizenResponseData"
        }
      }
    },
    "citizenvDeleteCitizenResponseData": {
      "type": "object"
    },
    "citizenvGetAdminDivOptionsResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvGetAdminDivOptionsResponseData"
        }
      }
    },
    "citizenvGetAdminDivOptionsResponseData": {
      "type": "object",
      "properties": {
        "adminDiv": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/citizenvAdminDiv"
          }
        }
      }
    },
    "citizenvGetAdminDivResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvGetAdminDivResponseData"
        }
      }
    },
    "citizenvGetAdminDivResponseData": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/DataResults"
          }
        },
        "pagination": {
          "$ref": "#/definitions/citizenvPagination"
        }
      }
    },
    "citizenvGetAuthResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvGetAuthResponseData"
        }
      }
    },
    "citizenvGetAuthResponseData": {
      "type": "object",
      "properties": {
        "user": {
          "$ref": "#/definitions/citizenvUser"
        }
      }
    },
    "citizenvGetCitizenResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvGetCitizenResponseData"
        }
      }
    },
    "citizenvGetCitizenResponseData": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/citizenvCitizen"
          }
        },
        "pagination": {
          "$ref": "#/definitions/citizenvPagination"
        }
      }
    },
    "citizenvGetOneAdminDivResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvGetOneAdminDivResponseData"
        }
      }
    },
    "citizenvGetOneAdminDivResponseData": {
      "type": "object",
      "properties": {
        "adminDiv": {
          "$ref": "#/definitions/citizenvAdminDiv"
        }
      }
    },
    "citizenvGetOneCitizenResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvGetOneCitizenResponseData"
        }
      }
    },
    "citizenvGetOneCitizenResponseData": {
      "type": "object",
      "properties": {
        "citizen": {
          "$ref": "#/definitions/citizenvCitizen"
        }
      }
    },
    "citizenvGetStatisticsCitizensResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvGetStatisticsCitizensResponseData"
        }
      }
    },
    "citizenvGetStatisticsCitizensResponseData": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/citizenvRecord"
          }
        }
      }
    },
    "citizenvGetUserOneResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvGetUserOneResponseData"
        }
      }
    },
    "citizenvGetUserOneResponseData": {
      "type": "object",
      "properties": {
        "user": {
          "$ref": "#/definitions/citizenvUser"
        }
      }
    },
    "citizenvGetUsersResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvGetUsersResponseData"
        }
      }
    },
    "citizenvGetUsersResponseData": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/citizenvUser"
          }
        },
        "pagination": {
          "$ref": "#/definitions/citizenvPagination"
        }
      }
    },
    "citizenvPagination": {
      "type": "object",
      "properties": {
        "total": {
          "type": "integer",
          "format": "int32"
        },
        "limit": {
          "type": "integer",
          "format": "int32"
        },
        "offset": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "citizenvPostAdminDivRequest": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "CallerId": {
          "type": "string"
        }
      }
    },
    "citizenvPostAdminDivResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvPostAdminDivResponseData"
        }
      }
    },
    "citizenvPostAdminDivResponseData": {
      "type": "object",
      "properties": {
        "admindiv": {
          "$ref": "#/definitions/citizenvAdminDiv"
        }
      }
    },
    "citizenvPostAuthPasswordRequest": {
      "type": "object",
      "properties": {
        "oldPassword": {
          "type": "string"
        },
        "newPassword": {
          "type": "string"
        },
        "CallerId": {
          "type": "string"
        }
      }
    },
    "citizenvPostAuthPasswordResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvPostAuthPasswordResponseData"
        }
      }
    },
    "citizenvPostAuthPasswordResponseData": {
      "type": "object"
    },
    "citizenvPostCampaignRequest": {
      "type": "object",
      "properties": {
        "CallerId": {
          "type": "string"
        },
        "startTime": {
          "type": "string",
          "format": "int64"
        },
        "endTime": {
          "type": "string",
          "format": "int64"
        },
        "codes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "citizenvPostCampaignResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvPostCampaignResponseData"
        }
      }
    },
    "citizenvPostCampaignResponseData": {
      "type": "object",
      "properties": {
        "campaign": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/citizenvCampaign"
          }
        }
      }
    },
    "citizenvPostCitizenRequest": {
      "type": "object",
      "properties": {
        "pid": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "birthday": {
          "type": "string",
          "format": "int64"
        },
        "gender": {
          "type": "string"
        },
        "nationality": {
          "type": "string"
        },
        "fatherName": {
          "type": "string"
        },
        "fatherPid": {
          "type": "string"
        },
        "motherName": {
          "type": "string"
        },
        "motherPid": {
          "type": "string"
        },
        "religion": {
          "type": "string"
        },
        "jobName": {
          "type": "string"
        },
        "educationalLevel": {
          "type": "string"
        },
        "CallerId": {
          "type": "string"
        },
        "currentPlaceCode": {
          "type": "string"
        },
        "residencePlaceCode": {
          "type": "string"
        },
        "hometownCode": {
          "type": "string"
        }
      }
    },
    "citizenvPostCitizenResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvPostCitizenResponseData"
        }
      }
    },
    "citizenvPostCitizenResponseData": {
      "type": "object",
      "properties": {
        "citizen": {
          "$ref": "#/definitions/citizenvCitizen"
        }
      }
    },
    "citizenvPostLoginRequest": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "citizenvPostLoginResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvPostLoginResponseData"
        }
      }
    },
    "citizenvPostLoginResponseData": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        },
        "useDefaultPassword": {
          "type": "boolean"
        }
      }
    },
    "citizenvPostRegisterRequest": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "citizenvPostRegisterResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvPostRegisterResponseData"
        }
      }
    },
    "citizenvPostRegisterResponseData": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "citizenvPostUserActiveResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvPostUserActiveResponseData"
        }
      }
    },
    "citizenvPostUserActiveResponseData": {
      "type": "object"
    },
    "citizenvPostUserIssueRequest": {
      "type": "object",
      "properties": {
        "CallerId": {
          "type": "string"
        },
        "adminDivCode": {
          "type": "string"
        }
      }
    },
    "citizenvPostUserIssueResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvPostUserIssueResponseData"
        }
      }
    },
    "citizenvPostUserIssueResponseData": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "citizenvPutOneAdminDivResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvPutOneAdminDivResponseData"
        }
      }
    },
    "citizenvPutOneAdminDivResponseData": {
      "type": "object"
    },
    "citizenvPutOneCitizenResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "data": {
          "$ref": "#/definitions/citizenvPutOneCitizenResponseData"
        }
      }
    },
    "citizenvPutOneCitizenResponseData": {
      "type": "object"
    },
    "citizenvRecord": {
      "type": "object",
      "properties": {
        "adminDivCode": {
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "age": {
          "type": "integer",
          "format": "int32"
        },
        "educationalLevel": {
          "type": "string"
        },
        "currentPlaceCode": {
          "type": "string"
        },
        "residencePlaceCode": {
          "type": "string"
        },
        "hometownCode": {
          "type": "string"
        },
        "jobName": {
          "type": "string"
        },
        "religion": {
          "type": "string"
        }
      }
    },
    "citizenvUser": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "adminDivId": {
          "type": "string"
        },
        "adminDivName": {
          "type": "string"
        },
        "roleId": {
          "type": "string"
        },
        "roleName": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "useDefaultPassword": {
          "type": "boolean"
        },
        "adminDivCode": {
          "type": "string"
        }
      }
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    }
  }
}
`
