// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/aqaurius6666/boilerplate-server-go/src/internal/api"
	"github.com/aqaurius6666/boilerplate-server-go/src/internal/db"
	"github.com/sirupsen/logrus"
)

// Injectors from server.wire.go:

func InitMainServer(ctx context.Context, logger2 *logrus.Logger, opts ServerOptions) (*Server, error) {
	dbDsn := opts.DBDsn
	serverRepo, err := db.InitServerRepo(ctx, logger2, dbDsn)
	if err != nil {
		return nil, err
	}
	apiServerOptions := api.ApiServerOptions{
		MainRepo: serverRepo,
	}
	apiServer, err := api.InitApiServer(ctx, logger2, apiServerOptions)
	if err != nil {
		return nil, err
	}
	server := &Server{
		ApiServer: apiServer,
		MainRepo:  serverRepo,
	}
	return server, nil
}

// server.wire.go:

type Server struct {
	ApiServer *api.ApiServer
	MainRepo  db.ServerRepo
}

type ServerOptions struct {
	DBDsn db.DBDsn
}
