// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package admindiv

import (
	"context"
	"github.com/aquarius6666/go-utils/database/cockroach"
	"github.com/aquarius6666/go-utils/logger"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from admindiv.cdb.wire.go:

func InitAdminDivCDBRepo(ctx context.Context, logger *logrus.Logger, db *gorm.DB) (*AdminDivCDBRepo, error) {
	cdbRepository := cockroach.InitCDBRepository(ctx, logger, db)
	adminDivCDBRepo := &AdminDivCDBRepo{
		CDBRepository: cdbRepository,
	}
	return adminDivCDBRepo, nil
}

func InitAdminDivCDBMockRepo(ctx context.Context, db *gorm.DB) (*AdminDivCDBRepo, error) {
	logrusLogger := logger.InitLoggerWithoutCLIContext()
	cdbRepository := cockroach.InitCDBRepository(ctx, logrusLogger, db)
	adminDivCDBRepo := &AdminDivCDBRepo{
		CDBRepository: cdbRepository,
	}
	return adminDivCDBRepo, nil
}
