// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package campaign

import (
	"context"
	"github.com/aqaurius6666/go-utils/database/cockroach"
	"github.com/aqaurius6666/go-utils/logger"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from campaign.cdb.wire.go:

func InitCampaignCDBRepo(ctx context.Context, logger *logrus.Logger, db *gorm.DB) (*CampaignCDBRepo, error) {
	cdbRepository := cockroach.InitCDBRepository(ctx, logger, db)
	campaignCDBRepo := &CampaignCDBRepo{
		CDBRepository: cdbRepository,
	}
	return campaignCDBRepo, nil
}

func InitRoleCDBMockRepo(ctx context.Context, db *gorm.DB) (*CampaignCDBRepo, error) {
	logrusLogger := logger.InitLoggerWithoutCLIContext()
	cdbRepository := cockroach.InitCDBRepository(ctx, logrusLogger, db)
	campaignCDBRepo := &CampaignCDBRepo{
		CDBRepository: cdbRepository,
	}
	return campaignCDBRepo, nil
}
