name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
#     - name: Run golangci-lint
#       uses: golangci/golangci-lint-action@v2.5.2
#     - name: Build
#       run: make build-image
    - name: Heroku-action
      run: |
        export HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku apps
        
        
