name: Go

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      uses: docker/setup-buildx-action@v1.6.0
    - name: Build
      run: make build-image
